on:
  # When Release Pull Request is opened and updated
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linter
        run: echo "${{github.event.pull_request.title}}" | npx commitlint
