# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'fix') || startsWith(github.event.pull_request.title, 'feat')
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Use cache 
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: yarn
      - name: Create NPMRC
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > ~/.npmrc
      - name: Git Setup
        run: |
          git config --global user.email "github-actions[bot]@github.com"
          git config --global user.name "github-actions[bot]"
      - name: Bump and Publish
        run: |
          yarn package:release
          git push --follow-tags origin master
          yarn package:publish
